### ISSUE TITLE
How to use a hover signal?

### ISSUE THREAD

**Issue by cmdcolin** [gky360/react-ngl#20]
Hi there

I was interested in using ngl with react and this looked like a great library. I wasn't sure how I could add a custom hover signal though.

Something similar to interactive/hover-tooltip https://nglviewer.org/ngl/gallery/index.html

The aim is not necessarily to do a custom tooltip but just make a custom listener for what atom is being moused over

**Comment by gky360** [comment]
Thank you for trying `react-ngl`!

I think the simplest way to make a custom listener is to get `stage` using `useStage` and set a listener to `stage`.
It will be like below.

```js
const stage = useStage();
const myListener = useCallback(() => { ... }, []);

useEffect(() => {
  stage.signals.hovered.add(myListener);
  return () => stage.signals.hovered.remove(myListener);
}, [myListener])
```

I hope this helps.

**Comment by cmdcolin** [comment]
ah interesting. I didn't see the useStage hook in the docs...I will give this a try!

**Comment by cmdcolin** [comment]
if I use the hook will I have to reimplement some of the logic of the stage HOC?

**Comment by gky360** [comment]
I don't think so.
You can implement the above example code in your component and render that component as children of `Stage` component.

**Comment by cmdcolin** [comment]
@gky360 thanks a bunch for the help...looking at this source code is a great guide for how to interface with a non-reacty type interface like NGL in general! I'll see what I can do

Thanks :)
