### ISSUE TITLE
Can't use defaultRepresentation

### ISSUE THREAD

**Issue by joemin** [gky360/react-ngl#22]
Hi! Thank you for making this wrapper, it's super useful!

I'm not sure about this, but I think there's an issue with how representations are handled when
```
{ defaultRepresentation: true }
```
is passed into loadFileParams for Component. The behavior is that the structure briefly flashes on screen (with the expected colorful defaultRepresentation) before disappearing, leaving just an empty Stage.

From briefly browsing around, I think what happens is that when the Component instance is created and [this](https://github.com/gky360/react-ngl/blob/9640209d555c881354d2d360c22b511661081f3b/src/components/Component/Component.tsx#L90-L97) runs:
```
  useEffect(() => {
    if (component) {
      component.removeAllRepresentations();
      reprList.forEach((repr) =>
        component.addRepresentation(repr.type, repr.params)
      );
    }
  }, [component, reprList]);
```
whatever representation was created from the first flag passed into loadFileParams is cleared out and it causes an empty Stage. I don't know if that's how it works under the hood, but I suspect that that may be the case.

I haven't tested this, but I think that changing the above to:
```
  useEffect(() => {
    if (component && reprList.length > 0) {
      component.removeAllRepresentations();
      reprList.forEach((repr) =>
        component.addRepresentation(repr.type, repr.params)
      );
    }
  }, [component, reprList]);
```
would allow for the `defaultRepresentation` flag to work as long as a reprList prop weren't passed in to Component.

Let me know what you think!

**Comment by gky360** [comment]
Thank you for reporting an issue!
I took a look into the code and confirmed that the default representation set by the `{ defaultRepresentation: true }` flag is overwritten by an empty `reprList`.

How about allowing `reprList` to be an uncontrolled prop?
That is, how about changing [default prop for `reprList` of `Component`](https://github.com/gky360/react-ngl/blob/master/src/components/Component/Component.tsx#L37) from `[]` to `undefined` and change the useEffect section to something like this?

```tsx
useEffect(() => {
  if (component && reprList) {
    component.removeAllRepresentations();
    reprList.forEach((repr) =>
      component.addRepresentation(repr.type, repr.params)
    );
  }
}, [component, reprList]);
```

By setting `reprList={undefined}`, representation is left uncontrolled by react-ngl and thus `{ defaultRepresentation: true}` flag of ngl will take effect.
By setting `reprList={[]}`, uses will still be able to clear representations.

**Comment by joemin** [comment]
yeah that looks good to me!
